export const EDITOR_OPTIONS = {
    options: [
        'inline',
        'blockType',
        'fontSize',
        'fontFamily',
        'textAlign',
        'colorPicker',
        'list',
        'link',
        'image',
        'history',
    ],
    inline: {
        options: ['bold', 'italic', 'underline', 'strikethrough'],
    },
    list: {
        options: ['unordered', 'ordered'],
    },
    fontFamily: {
        options: [
            'Arial',
            'Georgia',
            'Impact',
            'Tahoma',
            'Times New Roman',
            'Verdana',
        ],
    },
    colorPicker: {
        colors: [
            'rgb(0,0,0)',
            '#c92a2a',
            '#e67700',
            '#2b8a3e',
            '#364fc7',
            'rgb(255,255,255)',
            '#f03e3e',
            '#f59f00',
            '#37b24d',
            '#4263eb',
            'rgb(239,239,239)',
            '#ff6b6b',
            '#fcc419',
            '#51cf66',
            '#5c7cfa',
            'rgb(209,213,216)',
            '#ff8787',
            '#ffe066',
            '#8ce99a',
            '#91a7ff',
            'rgb(204,204,204)',
            '#ffc9c9',
            '#ffec99',
            '#b2f2bb',
            '#bac8ff',
        ],
    },
};
